title: "Desmond's Portfolio"
email: "desmond_ttm@hotmail.com"
description: "Showcasing my projects in electronics, robotics, and AI"
baseurl: "/portfolio"
url: "https://desmondttm123.github.io"
theme: jekyll-theme-cayman

github_username: desmondttm123
markdown: kramdown
