title: "Desmond's Portfolio"
email: "desmond_ttm@hotmail.com"
description: "Showcasing my projects in electronics, robotics, and AI"
baseurl: ""
url: "https://desmondttm123.github.io"
theme: jekyll-theme-midnight

plugins:
  - jekyll-feed
  - jekyll-seo-tag
